[project]
name = "flocky-gcp"
version = "0.1.0"
description = "Flocky is a line chat app for only my family."
authors = [
    {name = "yamashi4423",email = "yamashi4423@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "flask (>=3.1.0,<4.0.0)",
    "functions-framework (>=3.8.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
